# Generated by Django 4.1 on 2022-09-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('years', models.IntegerField()),
                ('born_in', models.DateField()),
                ('hobbie', models.CharField(max_length=50)),
            ],
        ),
    ]
