# Generated by Django 4.1 on 2022-09-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_family', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='name',
            new_name='nombre',
        ),
    ]
